language: bash
#os:
#  - linux
#  - osx
before_script:
  - source ./tests/setup_bats.sh
addons:
  hosts:
    - travis.dev
env:
  - GIT_SSH='ssh -o StrictHostKeyChecking=no'
install:
  - if [ "$(uname -s)" != "Darwin"  ]; then sudo apt-get update -qq && sudo apt-get install -y zsh; fi
script:
  - bats tests
notifications:
  email:
    on_success: never
